workflows:
  ios_build:
    name: Build iOS App without Code Signing
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        # Puedes agregar otras variables de entorno aquí si lo requieres
        IOS_CODE_SIGNING: "false"
    scripts:
      - flutter pub get
      - flutter build ios --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
